version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-env-variable:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "this is my name >> "
          command: echo ${My_Name}

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: echo " hello world !! from the output " > output.txt
       persist_to_workspace:
          root: ~/     # relative path to our working directory
          paths:      # file globs which will be persisted to the workspace
           - *

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      attach_workspace:
          at: ~/
      - run:
          command: cat output.txt
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-env-variable:
          requires: [say-hello]
      
