version: 2.1
commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID #<< parameters.to >>

jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-env-variable:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "this is my name >> "
          command: echo ${My_Name}
      - print_pipeline_id

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "create file"
          command: |
            echo " hello world !! from the output " > output.txt
      - persist_to_workspace:
          root: ~/    
          paths: 
           - ./*

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            cat output.txt

  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
workflows:
  my-workflow:
    jobs:
      - say-hello
      - print-env-variable:
          requires: [say-hello]
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]
      - create_infrastructure:
          requires: [print_output_file]

      
